import json
import requests
import os
import sys
from jwt_verify import create_access_token

sys.path.append(os.path.dirname(__file__))



def main():
    # create a token for user 1 (adjust as needed)
    token = create_access_token(user_id=1)
    cookies = {"access_token": token}

    # example payload for schedule generation
    payload = {
        "name": "My Test Schedule",
        "description": "Generated by test script",
        "term_id": 1,
        # each section must include fields expected by CourseContext
        "sections": [
            {
                "section": "CS 146 (Section 01)",
                "mode": "In Person",
                "unit": 3,
                "type": "LEC",
                "days": "MWF",
                "times": "09:00AM-10:15AM",
                "satifies": "MajorOnly",
                "location": "ENG305",
                "year": 2025,
                "semester": "Spring",
            },
            {
                "section": "CMPE 120 (Section 01)",
                "mode": "In Person",
                "unit": 3,
                "type": "LEC",
                "days": "TR",
                "times": "01:30PM-02:45PM",
                "satifies": "MajorOnly",
                "location": "ENG200",
                "year": 2025,
                "semester": "Spring",
            },
        ],
    }

    url = "http://localhost:8000/schedules/generate"
    print(f"POSTing to {url} with payload:\n{json.dumps(payload, indent=2)}\n")
    response = requests.post(url, json=payload, cookies=cookies)

    print("Status code:", response.status_code)
    try:
        print("Response JSON:", json.dumps(response.json(), indent=2))
    except ValueError:
        print("Non-JSON response:\n", response.text)


if __name__ == "__main__":
    main()
