import json
import requests
import os
import sys


sys.path.append(os.path.dirname(__file__))
from jwt_verify import create_access_token


def main():
    # create a token for user 1 (adjust as needed)
    token = create_access_token(user_id=1)
    cookies = {"access_token": token}

    # example payload for schedule generation
    payload = {
        "name": "My Test Schedule",
        "description": "Generated by test script",
        "term_id": 1,
        "sections": [
            {"course_id": "CS101", "section": "A"},
            {"course_id": "MATH200", "section": "B"}
        ],
    }

    url = "http://localhost:8000/schedules/generate"
    print(f"POSTing to {url} with payload:\n{json.dumps(payload, indent=2)}\n")
    response = requests.post(url, json=payload, cookies=cookies)

    print("Status code:", response.status_code)
    try:
        print("Response JSON:", json.dumps(response.json(), indent=2))
    except ValueError:
        print("Non-JSON response:\n", response.text)


if __name__ == "__main__":
    main()
