const ProfessorLinksRMP = {
    "Aamina Ahmad": "https://www.ratemyprofessors.com/professor/2319083",
  "Aaron Romanowsky": "https://www.ratemyprofessors.com/professor/2896331",
  "Abbas Moallem": "https://www.ratemyprofessors.com/professor/902123",
  "Abera Jiru": "https://www.ratemyprofessors.com/professor/1557300",
  "Abhay Vinayak Mutalik Desai": null,
  "Abhishek Gaikwad": "https://www.ratemyprofessors.com/professor/2822613",
  "Abhishek Golla": null,
  "Adam Smith": null,
  "Addie Mahmassani": "https://www.ratemyprofessors.com/professor/2866819",
  "Adi Siva Prasad Reddy Korivi": null,
  "Aditya Kumar": null,
  "Aditya Nagaraj Shanbhog": null,
  "Adrian Juanson": null,
  "Ahmad Yazdankhah": "https://www.ratemyprofessors.com/professor/1919535",
  "Ahmed Banafa": "https://www.ratemyprofessors.com/professor/2228841",
  "Ahmed Ezzat": "https://www.ratemyprofessors.com/professor/1930235",
  "Ahmet Bindal": "https://www.ratemyprofessors.com/professor/275974",
  "Alan Meyer / Jonathan Miller": "https://www.ratemyprofessors.com/professor/2754461",
  "Alan Meyer / Ryan Portner": "https://www.ratemyprofessors.com/professor/2754461",
  "Alana Bailey": "https://www.ratemyprofessors.com/professor/2652827",
  "Alayna Mills": "https://www.ratemyprofessors.com/professor/2539905",
  "Albert Chang": "https://www.ratemyprofessors.com/professor/2814399",
  "Alee Corsiglia": null,
  "Alejandro Garcia": null,
  "Aleksandra Gorka": "https://www.ratemyprofessors.com/professor/2919348",
  "Alesya Petty": "https://www.ratemyprofessors.com/professor/1853974",
  "Alex Davis": null,
  "Alex May": null,
  "Alex Vargas": null,
  "Alexander Cabot": null,
  "Alexandra Chakarov": "https://www.ratemyprofessors.com/professor/2709680",
  "Alexi Musick": "https://www.ratemyprofessors.com/professor/2874070",
  "Alexis Cutchin": "https://www.ratemyprofessors.com/professor/2725663",
  "Alla Petrosyan": "https://www.ratemyprofessors.com/professor/2793040",
  "Allison Gregory": "https://www.ratemyprofessors.com/professor/2950524",
  "Allison Harness": "https://www.ratemyprofessors.com/professor/2215085",
  "Allison Stdennis": "https://www.ratemyprofessors.com/professor/2819317",
  "Alondra Torres Contreras": null,
  "Amanda Frank": null,
  "Amanda Shipman": null,
  "Amanda Smith": "https://www.ratemyprofessors.com/professor/2083137",
  "Amber Sylva": "https://www.ratemyprofessors.com/professor/2526746",
  "Amelia Le": null,
  "Amin Termeh Yousefi": "https://www.ratemyprofessors.com/professor/2667982",
  "Ammar Rayes": "https://www.ratemyprofessors.com/professor/1215145",
  "Amna Yusuf": "https://www.ratemyprofessors.com/professor/2738596",
  "Amulya Raavi": null,
  "Anant Shukla": "https://www.ratemyprofessors.com/professor/2946225",
  "Andrea Gottlieb": "https://www.ratemyprofessors.com/professor/1822658",
  "Andrew Bond": "https://www.ratemyprofessors.com/professor/2085039",
  "Andrew Kinter": null,
  "Andrew Mcclure": null,
  "Anindita Bhattacharya": "https://www.ratemyprofessors.com/professor/2319259",
  "Anne Cheilek": "https://www.ratemyprofessors.com/professor/2918841",
  "Anne Walker": "https://www.ratemyprofessors.com/professor/2869656",
  "Anqi Shao": "https://www.ratemyprofessors.com/professor/2789247",
  "Apoorva Mohite": "https://www.ratemyprofessors.com/professor/2967991",
  "Aravind Rokkam": "https://www.ratemyprofessors.com/professor/2990954",
  "Arman Medina": "https://www.ratemyprofessors.com/professor/2149593",
  "Artur Antonyan": null,
  "Ashley Van Dyne / Jonathan Miller": "https://www.ratemyprofessors.com/professor/1660052",
  "Athanasios Hatzikoutelis": "https://www.ratemyprofessors.com/professor/2608985",
  "Athanasios Hatzikoutelis / Daniel Olson": "https://www.ratemyprofessors.com/professor/2608985",
  "Au-Co Tran": "https://www.ratemyprofessors.com/professor/2446214",
  "Austin Karwowski": "https://www.ratemyprofessors.com/professor/2955745",
  "Avantiak Rohatgi": "https://www.ratemyprofessors.com/professor/1218201",
  "Avantika Rohatgi": "https://www.ratemyprofessors.com/professor/1218201",
  "Aydin Kiasat": null,
  "Azadeh Shahid Faylienejad": "https://www.ratemyprofessors.com/professor/2595694",
  "Baixue Zhang": null,
  "Bala Meghana Shivani Sripathi Panditharadhyula": null,
  "Balaji Venkatraman": "https://www.ratemyprofessors.com/professor/1971472",
  "Barbara Murphywesley": "https://www.ratemyprofessors.com/professor/2220649",
  "Barbara Wortham": "https://www.ratemyprofessors.com/professor/2772513",
  "Bee Leng Lee": "https://www.ratemyprofessors.com/professor/759840",
  "Bem Cayco": null,
  "Ben Reed": "https://www.ratemyprofessors.com/professor/2426648",
  "Bennett Haffner": "https://www.ratemyprofessors.com/professor/3036274",
  "Bhargavibahen Trivedi": "https://www.ratemyprofessors.com/professor/2868624",
  "Bhaskar Mantha": "https://www.ratemyprofessors.com/professor/2328218",
  "Bhaummi Patel": null,
  "Bhawandeep Singh Harsh": "https://www.ratemyprofessors.com/professor/2557097",
  "Bhawandeep Singh Harsh / Harjot Singh": "https://www.ratemyprofessors.com/professor/2557097",
  "Bhawandeep Singh Harsh / Prashansa Evangeline Bonapalle": "https://www.ratemyprofessors.com/professor/2557097",
  "Bhawandeep Singh Harsh / Sanjayvarma Pandeti": "https://www.ratemyprofessors.com/professor/2557097",
  "Bhawandeep Singh Harsh / Shireen Faraha Shaik": "https://www.ratemyprofessors.com/professor/2557097",
  "Binh Le": "https://www.ratemyprofessors.com/professor/2536101",
  "Bonnie Hsia": "https://www.ratemyprofessors.com/professor/1169954",
  "Bradley Buerer / Ryan Portner": "https://www.ratemyprofessors.com/professor/2594645",
  "Bramarambika Puligilla": null,
  "Brandon Barrios": null,
  "Brandon Garcia": null,
  "Brandon White": "https://www.ratemyprofessors.com/professor/984189",
  "Brenda Lopez Rodas": "https://www.ratemyprofessors.com/professor/2844983",
  "Brenda Serrano": "https://www.ratemyprofessors.com/professor/526463",
  "Brenda Serrano / Karen Singmaster": "https://www.ratemyprofessors.com/professor/2828020",
  "Brian Tsao": null,
  "Brianne Gutmann": "https://www.ratemyprofessors.com/professor/2319179",
  "Brooke Bellinghausen": null,
  "Calvin Jumawan": null,
  "Carl Bugarin": "https://www.ratemyprofessors.com/professor/115898",
  "Carlie Pietsch / Gabriela Diaz Santana": "https://www.ratemyprofessors.com/professor/2381055",
  "Carlie Pietsch / Jeffrey Wegener": "https://www.ratemyprofessors.com/professor/2381055",
  "Carlie Pietsch / Joseph Petsche": "https://www.ratemyprofessors.com/professor/2381055",
  "Carlie Pietsch / Mayra Dudrenova": "https://www.ratemyprofessors.com/professor/2381055",
  "Carlie Pietsch / Michele Dodge": "https://www.ratemyprofessors.com/professor/2381055",
  "Carlie Pietsch / Raymond Hess": "https://www.ratemyprofessors.com/professor/2381055",
  "Carlos Rojas": "https://www.ratemyprofessors.com/professor/2598966",
  "Cassie Blair": null,
  "Chandra Prakash Saini": null,
  "Chandrasekar Vuppalapati": "https://www.ratemyprofessors.com/professor/1982139",
  "Chandrasekhar Mukherjee": "https://www.ratemyprofessors.com/professor/2803427",
  "Chang Choo": "https://www.ratemyprofessors.com/professor/63512",
  "Chang Choo / Thuy Le": "https://www.ratemyprofessors.com/professor/63512",
  "Chao-Li Tarng": "https://www.ratemyprofessors.com/professor/1791734",
  "Charan Bhaskar": "https://www.ratemyprofessors.com/professor/2803679",
  "Charity Wei": null,
  "Charlize Kusuma": null,
  "Chelsea Criez": "https://www.ratemyprofessors.com/professor/2414516",
  "Chendhra Sheker Nagula": null,
  "Chi Phan": "https://www.ratemyprofessors.com/professor/3101561",
  "Ching-Seh Wu": "https://www.ratemyprofessors.com/professor/2285136",
  "Chinmay Nilesh Mahagaonkar": "https://www.ratemyprofessors.com/professor/2980153",
  "Chinmayi Kagganagi": null,
  "Chloe Tannous": null,
  "Chris Tseng": "https://www.ratemyprofessors.com/professor/213630",
  "Christina Peters": "https://www.ratemyprofessors.com/professor/1871311",
  "Christopher Bankston": "https://www.ratemyprofessors.com/professor/1871311",
  "Christopher Dizon": "https://www.ratemyprofessors.com/professor/2636209",
  "Christopher Pollett": "https://www.ratemyprofessors.com/professor/214943",
  "Chung-Wen Tsao": "https://www.ratemyprofessors.com/professor/2318479",
  "Clare Cordero": "https://www.ratemyprofessors.com/professor/1728115",
  "Clarissa Smith / Jonathan Miller": null,
  "Clarissa Smith / Ryan Portner": null,
  "Colton Saylor": "https://www.ratemyprofessors.com/professor/2398551",
  "Craig England": "https://www.ratemyprofessors.com/professor/2770900",
  "Craig Jones": "https://www.ratemyprofessors.com/professor/2485366",
  "Cristina Tortora": null,
  "Curtis Asplund": "https://www.ratemyprofessors.com/professor/2913531",
  "Dahyun Oh": "https://www.ratemyprofessors.com/professor/2278007",
  "Dan Le": "https://www.ratemyprofessors.com/professor/3029790",
  "Dan Xiao": null,
  "Daniel Brinkman": "https://www.ratemyprofessors.com/professor/2227385",
  "Daniel Hendel De La O": "https://www.ratemyprofessors.com/professor/1220007",
  "Daniel Olson": "https://www.ratemyprofessors.com/professor/2800712",
  "Danielle Allen": "https://www.ratemyprofessors.com/professor/3008256",
  "Danny Barringer": "https://www.ratemyprofessors.com/professor/2909385",
  "Daphne Chen": "https://www.ratemyprofessors.com/professor/3103524",
  "Darrian Ellis-Hardin": null,
  "Dashiell Fryer": "https://www.ratemyprofessors.com/professor/2080877",
  "David Archer": "https://www.ratemyprofessors.com/professor/2941336",
  "David Brook": "https://www.ratemyprofessors.com/professor/959205",
  "David Coad": "https://www.ratemyprofessors.com/professor/1688111",
  "David Goulette": "https://www.ratemyprofessors.com/professor/1907101",
  "David Parent": "https://www.ratemyprofessors.com/professor/62045",
  "David Santiago": null,
  "David Taylor": "https://www.ratemyprofessors.com/professor/214947",
  "Dawit Yerdea": null,
  "Debra Caires": "https://www.ratemyprofessors.com/professor/244307",
  "Deep Shah": "https://www.ratemyprofessors.com/professor/2983148",
  "Deeptiman Kaushik": null,
  "Denise Gip": null,
  "Derek Mena Godoy": "https://www.ratemyprofessors.com/professor/2820760",
  "Derek Mena Godoy / Ryan Portner": "https://www.ratemyprofessors.com/professor/2820760",
  "Devam Sanjay Sheth": "https://www.ratemyprofessors.com/professor/3062870",
  "Dharmik Vijay Joshi": null,
  "Dhruv Jatinbhai Kapadia": null,
  "Dillion Chen": null,
  "Dolly Estrada": "https://www.ratemyprofessors.com/professor/2919349",
  "Dominic Abucejo": "https://www.ratemyprofessors.com/professor/1969051",
  "Doug Case": "https://www.ratemyprofessors.com/professor/3015141",
  "Edgar Bering": "https://www.ratemyprofessors.com/professor/2856785",
  "Edric Dabu": "https://www.ratemyprofessors.com/professor/3067613",
  "Ehsan Khatami": null,
  "Elaheh Sigari": "https://www.ratemyprofessors.com/professor/2439044",
  "Elizabeth Migicovsky": "https://www.ratemyprofessors.com/professor/2494046",
  "Elizabeth Sonnier": "https://www.ratemyprofessors.com/professor/783120",
  "Ellie Murdoch / Carlie Pietsch": null,
  "Emi Ishida": "https://www.ratemyprofessors.com/professor/2377557",
  "Emiliano Lopez Ruiz": null,
  "Eric Vanuska": "https://www.ratemyprofessors.com/professor/2992239",
  "Erik Johnson": "https://www.ratemyprofessors.com/professor/2539642",
  "Essam Marouf": "https://www.ratemyprofessors.com/professor/222709",
  "Ethan Hasenauer": null,
  "Ethel Tshukudu": "https://www.ratemyprofessors.com/professor/3029157",
  "Étienne Brown": "https://www.ratemyprofessors.com/professor/2565921",
  "Eugene Ionel": "https://www.ratemyprofessors.com/professor/26063",
  "Eveline Bellegarda": "https://www.ratemyprofessors.com/professor/2220885",
  "Fabio Di Troia": "https://www.ratemyprofessors.com/professor/2116397",
  "Faith Kirk": "https://www.ratemyprofessors.com/professor/2253715",
  "Faramarz Mortezaie": "https://www.ratemyprofessors.com/professor/2148983",
  "Faranak Abri": "https://www.ratemyprofessors.com/professor/2824127",
  "Farshid Marbouti": "https://www.ratemyprofessors.com/professor/2523139",
  "Ferdinand Rivera": "https://www.ratemyprofessors.com/professor/221066",
  "Fiona Su": null,
  "Frank Butt": "https://www.ratemyprofessors.com/professor/115849",
  "Frank Lin": "https://www.ratemyprofessors.com/professor/446690",
  "Frederick Vincent": "https://www.ratemyprofessors.com/professor/2646919",
  "Gaurav Sarkar": null,
  "Genevieve Nguyen": null,
  "Gheorghi Guzun": "https://www.ratemyprofessors.com/professor/2286678",
  "Giang Le": "https://www.ratemyprofessors.com/professor/2497026",
  "Gianni Giordanengo": "https://www.ratemyprofessors.com/professor/2805558",
  "Gil Zamora": "https://www.ratemyprofessors.com/professor/2597236",
  "Gilles Muller": "https://www.ratemyprofessors.com/professor/2508108",
  "Gina Quan": "https://www.ratemyprofessors.com/professor/2468002",
  "Glenn Friedman": "https://www.ratemyprofessors.com/professor/2748068",
  "Gokay Saldamli": "https://www.ratemyprofessors.com/professor/2180959",
  "Gokul Sriram Guptha Maremalla": null,
  "Gregory Courand": "https://www.ratemyprofessors.com/professor/2802659",
  "Gregory Tomlinson": "https://www.ratemyprofessors.com/professor/2867334",
  "Guangliang Chen": "https://www.ratemyprofessors.com/professor/1941199",
  "Hadley Debrine": "https://www.ratemyprofessors.com/professor/2979172",
  "Haipeng Gao": null,
  "Haluk Ozemek": "https://www.ratemyprofessors.com/professor/103125",
  "Hao Thai": "https://www.ratemyprofessors.com/professor/3146866",
  "Haonan Wang": "https://www.ratemyprofessors.com/professor/2769234",
  "Harika Kolipaka": null,
  "Hee Park": null,
  "Heidi Eisips": "https://www.ratemyprofessors.com/professor/2488670",
  "Helen Meservey": "https://www.ratemyprofessors.com/professor/2340169",
  "Hidefumi Katsuura": "https://www.ratemyprofessors.com/professor/54073",
  "Hien Vo": null,
  "Hilary Hurst": "https://www.ratemyprofessors.com/professor/2953061",
  "Hitanshu Ashok Patel": null,
  "Hiu Yung Wong": "https://www.ratemyprofessors.com/professor/2498167",
  "Hollianne Mcclure": "https://www.ratemyprofessors.com/professor/2636150",
  "Hollianne Mcclure / Jonathan Miller": "https://www.ratemyprofessors.com/professor/2636150",
  "Hossein Omidian": null,
  "Hrishikesh Ravish": null,
  "Hsin-Yi Meng": "https://www.ratemyprofessors.com/professor/2066054",
  "Huiling Xie": null,
  "Ian Power-Luetscher": "https://www.ratemyprofessors.com/professor/2725393",
  "Iftiza Ahmed Shovon": null,
  "Ignacio Mosqueira": "https://www.ratemyprofessors.com/professor/949495",
  "Igor Tyukhov": "https://www.ratemyprofessors.com/professor/2441734",
  "Inez Yuwanita": "https://www.ratemyprofessors.com/professor/2562961",
  "Irina Slobodov": "https://www.ratemyprofessors.com/professor/2969955",
  "Ishie Eswar": "https://www.ratemyprofessors.com/professor/1846569",
  "Ivy Tran": null,
  "Jack Warecki": "https://www.ratemyprofessors.com/professor/2220317",
  "Jacob Akers": null,
  "Jahan Ghofraniha": "https://www.ratemyprofessors.com/professor/857594",
  "Jalel Rejeb": "https://www.ratemyprofessors.com/professor/1145910",
  "Jane Berg": null,
  "Jane Huynh": "https://www.ratemyprofessors.com/professor/2585795",
  "Jason Pruitt": "https://www.ratemyprofessors.com/professor/2906686",
  "Javier Cardoza-Kon": "https://www.ratemyprofessors.com/professor/2494042",
  "Javier Valencia": "https://www.ratemyprofessors.com/professor/1844513",
  "Jeffrey Beckstrand": null,
  "Jeffrey Wegener / Carlie Pietsch": null,
  "Jehanzeb Khan": null,
  "Jennifer Bean": "https://www.ratemyprofessors.com/professor/2724460",
  "Jennifer Johnston": "https://www.ratemyprofessors.com/professor/2313466",
  "Jeonghee Kim": "https://www.ratemyprofessors.com/professor/944272",
  "Jesse Geneson": "https://www.ratemyprofessors.com/professor/2654864",
  "Jessica Williamson / Jonathan Miller": "https://www.ratemyprofessors.com/professor/2636257",
  "Jillian Murphy": "https://www.ratemyprofessors.com/professor/2832085",
  "John Cooper": null,
  "John Diniz": "https://www.ratemyprofessors.com/professor/2806439",
  "John Leih": "https://www.ratemyprofessors.com/professor/1166186",
  "Johnny Damm": "https://www.ratemyprofessors.com/professor/2538290",
  "Jon Pearce": "https://www.ratemyprofessors.com/professor/243000",
  "Jon Richey": "https://www.ratemyprofessors.com/professor/3031519",
  "Jonas Fahrney": null,
  "Jonathan Lauffer": "https://www.ratemyprofessors.com/professor/3105742",
  "Jonathan Miller / Alan Meyer": "https://www.ratemyprofessors.com/professor/492808",
  "Jonathan Miller / Derek Mena Godoy": "https://www.ratemyprofessors.com/professor/492808",
  "Jonathan Miller / Hollianne Mcclure": "https://www.ratemyprofessors.com/professor/492808",
  "Jonathan Miller / Ricky Ede": "https://www.ratemyprofessors.com/professor/492808",
  "Jonathan Miller / Robert Meyer": "https://www.ratemyprofessors.com/professor/492808",
  "Jonathan Miller / Ryan Portner": "https://www.ratemyprofessors.com/professor/492808",
  "Jonathan Miller / Samantha Hamada": "https://www.ratemyprofessors.com/professor/492808",
  "Jonathan Miller / Simone Yeager": "https://www.ratemyprofessors.com/professor/492808",
  "Jonathan Miller / Will Rizza": "https://www.ratemyprofessors.com/professor/492808",
  "Jonathan Ponniah": "https://www.ratemyprofessors.com/professor/2296588",
  "Jonathan Ponniah / Thuy Le": "https://www.ratemyprofessors.com/professor/2296588",
  "Jordan Ellis": "https://www.ratemyprofessors.com/professor/3066015",
  "Jordan Schettler": "https://www.ratemyprofessors.com/professor/2088811",
  "Jose Ramirez": "https://www.ratemyprofessors.com/professor/2970992",
  "Jose Villagrana": "https://www.ratemyprofessors.com/professor/2519331",
  "Joseph Navarro": "https://www.ratemyprofessors.com/professor/2280219",
  "Joseph Petsche": "https://www.ratemyprofessors.com/professor/2563406",
  "Joseph Petsche / Carlie Pietsch": "https://www.ratemyprofessors.com/professor/2563406",
  "Joseph Petsche / Ryan Portner": "https://www.ratemyprofessors.com/professor/2563406",
  "Joshita Atmakuri": null,
  "Juan Gomez": "https://www.ratemyprofessors.com/professor/1570635",
  "Jun Liu": "https://www.ratemyprofessors.com/professor/2974343",
  "Juzi Zhao": "https://www.ratemyprofessors.com/professor/2319241",
  "K Ghadiri": "https://www.ratemyprofessors.com/professor/529741",
  "Kai Mast": null,
  "Kaikai Liu": "https://www.ratemyprofessors.com/professor/2220589",
  "Kala Padmanabhan": "https://www.ratemyprofessors.com/professor/2555642",
  "Karen Liou": "https://www.ratemyprofessors.com/professor/3065409",
  "Karen Moody": null,
  "Karen Singmaster": "https://www.ratemyprofessors.com/professor/26839",
  "Karen Singmaster / Brenda Serrano": "https://www.ratemyprofessors.com/professor/26839",
  "Karen Singmaster / Elizabeth Migicovsky": "https://www.ratemyprofessors.com/professor/26839",
  "Karen Singmaster / Melody Esfandiari": "https://www.ratemyprofessors.com/professor/26839",
  "Karthik Bharadwaj Kunigal Raveendra": null,
  "Kashi Nath": "https://www.ratemyprofessors.com/professor/2884885",
  "Kassahun Betre": null,
  "Katerina Potika": "https://www.ratemyprofessors.com/professor/2099184",
  "Katharine Studer": "https://www.ratemyprofessors.com/professor/2804429",
  "Katherine D. Harris": "https://www.ratemyprofessors.com/professor/765808",
  "Katherine Hamilton": null,
  "Katherine Soohoo": null,
  "Kaushik Patra": "https://www.ratemyprofessors.com/professor/1977127",
  "Kay Liou": "https://www.ratemyprofessors.com/professor/3105817",
  "Ken Tsang": "https://www.ratemyprofessors.com/professor/2778566",
  "Kenneth Wharton": "https://www.ratemyprofessors.com/professor/305291",
  "Kevin Moore": "https://www.ratemyprofessors.com/professor/439511",
  "Kevin Nguyen": "https://www.ratemyprofessors.com/professor/2879445",
  "Kevin Pham": null,
  "Kevin Schmidt": null,
  "Khushbu Shah": null,
  "Kirsten Schwartz": "https://www.ratemyprofessors.com/professor/2302023",
  "Kong Li": "https://www.ratemyprofessors.com/professor/1884355",
  "Kourosh Youssefi": "https://www.ratemyprofessors.com/professor/79259",
  "Krista Wirth": "https://www.ratemyprofessors.com/professor/2348327",
  "Kristian O'Hare": "https://www.ratemyprofessors.com/professor/2640037",
  "Kristin Fitzpatrick Ezell": "https://www.ratemyprofessors.com/professor/2661443",
  "Kunjal Shah": null,
  "Kyle Hambrook": "https://www.ratemyprofessors.com/professor/2497500",
  "Kyle Nguyen": null,
  "Kyle Worley": null,
  "Kyle Yrigoyen": null,
  "Laksh Lavish Thakkar": null,
  "Lakshmi Ananya Mandava": null,
  "Laura Kapitzky": "https://www.ratemyprofessors.com/professor/2647659",
  "Laura Mugica": null,
  "Laura Mugica Sanchez": "https://www.ratemyprofessors.com/professor/2902273",
  "Lavanya Lankalapilli": null,
  "Lawrence Nguyen": null,
  "Leanne Lindelof": "https://www.ratemyprofessors.com/professor/342195",
  "Lee Patterson": "https://www.ratemyprofessors.com/professor/2799735",
  "Liam Stanton": "https://www.ratemyprofessors.com/professor/2415970",
  "Likith Sodishetty Venkataramana": null,
  "Lili He": "https://www.ratemyprofessors.com/professor/1260286",
  "Lilly Chen": "https://www.ratemyprofessors.com/professor/2702608",
  "Lin Zou": "https://www.ratemyprofessors.com/professor/1870648",
  "Linda Landau": "https://www.ratemyprofessors.com/professor/1856237",
  "Linh Pham": null,
  "Lining Wang": "https://www.ratemyprofessors.com/professor/2841157",
  "Liz Asborno": "https://www.ratemyprofessors.com/professor/3050972",
  "Loc Lam": "https://www.ratemyprofessors.com/professor/2548623",
  "Logan Miller": "https://www.ratemyprofessors.com/professor/2953059",
  "Logan O'Brien": "https://www.ratemyprofessors.com/professor/3101696",
  "Lucero Sandoval": null,
  "Madeline Doyle": null,
  "Jonathan Miller": "https://www.ratemyprofessors.com/professor/492808",
  "Mahathi Sritha Gudimella": null,
  "Mahekkumar Mayankkumar Pavthawala": null,
  "Mahima Agumbe Suresh": "https://www.ratemyprofessors.com/professor/2511724",
  "Mahima Agumbe Suresh / Ishie Eswar": "https://www.ratemyprofessors.com/professor/2511724",
  "Malik Oliver": null,
  "Manoj Kumar Gundu": null,
  "Manvendrasinh Sisodia": "https://www.ratemyprofessors.com/professor/3139308",
  "Mario Chris": "https://www.ratemyprofessors.com/professor/2747628",
  "Marion Campisi": "https://www.ratemyprofessors.com/professor/2079236",
  "Mark Ammar Rayes": "https://www.ratemyprofessors.com/professor/1215145",
  "Mark Dowdy": "https://www.ratemyprofessors.com/professor/1201880",
  "Mark Stamp": "https://www.ratemyprofessors.com/professor/281383",
  "Martina Bremer": "https://www.ratemyprofessors.com/professor/1037129",
  "Mary Poffenroth": "https://www.ratemyprofessors.com/professor/1062099",
  "Maryam Khazaei Pool": "https://www.ratemyprofessors.com/professor/3065699",
  "Maryam Pirmoradi": null,
  "Matt Villamarin": null,
  "Matthew Leigh": "https://www.ratemyprofessors.com/professor/2380723",
  "Matthew Leigh / Jon Richey": "https://www.ratemyprofessors.com/professor/2380723",
  "Matthew Leigh / Jonathan Miller": "https://www.ratemyprofessors.com/professor/2380723",
  "Matthew Leigh / Ryan Portner": "https://www.ratemyprofessors.com/professor/2380723",
  "Max Rivera": "https://www.ratemyprofessors.com/professor/2654025",
  "Maxine Shao": "https://www.ratemyprofessors.com/professor/106503",
  "Medha Bodas": "https://www.ratemyprofessors.com/professor/57992",
  "Meghna Shankar": null,
  "Melody Esfandiari": "https://www.ratemyprofessors.com/professor/1148403",
  "Micah Johnson": "https://www.ratemyprofessors.com/professor/2975925",
  "Michae Musick": null,
  "Michael Edegrton": "https://www.ratemyprofessors.com/professor/2604706",
  "Michael Edgerton": "https://www.ratemyprofessors.com/professor/2604706",
  "Michael Ford": "https://www.ratemyprofessors.com/professor/3100595",
  "Michael Lam": "https://www.ratemyprofessors.com/professor/2926677",
  "Michael Vartanian": "https://www.ratemyprofessors.com/professor/1152117",
  "Michele Dodge": null,
  "Michele Dodge / Carlie Pietsch": null,
  "Mike Wood": "https://www.ratemyprofessors.com/professor/2922737",
  "Minh Hoang Huynh": "https://www.ratemyprofessors.com/professor/3114176",
  "Minh Vu": "https://www.ratemyprofessors.com/professor/2078573",
  "Misako Van Der Poel": "https://www.ratemyprofessors.com/professor/958914",
  "Mohammad Saleem": null,
  "Mohammed Yahdi": "https://www.ratemyprofessors.com/professor/2499659",
  "Monique Howe": null,
  "Mostafa Jalal": "https://www.ratemyprofessors.com/professor/2533454",
  "Muhammad Saeed": null,
  "Mukesh Dokala": null,
  "Murat Bulut": "https://www.ratemyprofessors.com/professor/2071863",
  "Murat Okyar": "https://www.ratemyprofessors.com/professor/2904220",
  "Nada Attar": "https://www.ratemyprofessors.com/professor/2445092",
  "Nader Mir": "https://www.ratemyprofessors.com/professor/234231",
  "Naga Vardhan Maddala": null,
  "Nalana La Framboise": "https://www.ratemyprofessors.com/professor/3017094",
  "Narayan Balasubramanian": "https://www.ratemyprofessors.com/professor/2988718",
  "Nargis Adham": "https://www.ratemyprofessors.com/professor/2813956",
  "Nargis Adham / Azadeh Shahid Faylienejad": "https://www.ratemyprofessors.com/professor/2813956",
  "Nathan Lewis": null,
  "Nathan Samarasena": "https://www.ratemyprofessors.com/professor/3130469",
  "Nathapong Shugan": "https://www.ratemyprofessors.com/professor/2508596",
  "Navrati Saxena": "https://www.ratemyprofessors.com/professor/2626481",
  "Neil Switz": "https://www.ratemyprofessors.com/professor/2339653",
  "Neomi Millan": null,
  "Nica Tanaka": "https://www.ratemyprofessors.com/professor/3055796",
  "Nick Sobrepena": null,
  "Nidhi Zare": "https://www.ratemyprofessors.com/professor/2932442",
  "Nikhil Sunku": null,
  "Nikhil Vaitla": null,
  "Niloofar Salehi": "https://www.ratemyprofessors.com/professor/995295",
  "Niranjani Patel": null,
  "Nithin Reddy Govindugari": null,
  "Nivedita Nair": null,
  "Noel Dasi": null,
  "Noel Smith Dasi": null,
  "Nora Adadurova": "https://www.ratemyprofessors.com/professor/3094101",
  "Olenka Hubickyj": "https://www.ratemyprofessors.com/professor/1142532",
  "Olga Kovaleva": "https://www.ratemyprofessors.com/professor/89392",
  "Padmavati Tanniru": "https://www.ratemyprofessors.com/professor/1152116",
  "Parul Bansal": null,
  "Patrick Murphy": "https://www.ratemyprofessors.com/professor/2940775",
  "Paul Houck": "https://www.ratemyprofessors.com/professor/1570468",
  "Paul Houck / Nargis Adham": "https://www.ratemyprofessors.com/professor/1570468",
  "Paul Nguyen": "https://www.ratemyprofessors.com/professor/2553649",
  "Paul Sanghera": "https://www.ratemyprofessors.com/professor/89841",
  "Paul Varun Guddeti": null,
  "Pavan Kumar Bajjuri": null,
  "Pavan Nageswar Reddy Bodavarapu": null,
  "Peter Beyersdorf": "https://www.ratemyprofessors.com/professor/745293",
  "Peter Beyersdorf / Kenneth Wharton": "https://www.ratemyprofessors.com/professor/745293",
  "Peter Gao": "https://www.ratemyprofessors.com/professor/2938031",
  "Peter O'Sullivan": "https://www.ratemyprofessors.com/professor/656737",
  "Philip Avila": null,
  "Phillip Hawkins": "https://www.ratemyprofessors.com/professor/2106650",
  "Phuong Phan": "https://www.ratemyprofessors.com/professor/2834704",
  "Ping Hsu": "https://www.ratemyprofessors.com/professor/1198947",
  "Pinky Mathew": "https://www.ratemyprofessors.com/professor/2805395",
  "Plamen Koev": "https://www.ratemyprofessors.com/professor/1218803",
  "Poojan Bharatbhai Gandhi": null,
  "Pouya Ostovari": "https://www.ratemyprofessors.com/professor/2603962",
  "Pranathi Kunadi": "https://www.ratemyprofessors.com/professor/2975367",
  "Pranavi Chaturvedula": "https://www.ratemyprofessors.com/professor/2985100",
  "Pranitha Harani Koka": null,
  "Pranjali Sanghvi": null,
  "Pranusha Cheemarla": null,
  "Prashansa Evangeline Bonapalle / Bhawandeep Singh Harsh": null,
  "Pratik Korat": null,
  "Prayuj Pillai": null,
  "Preetpal Kang": "https://www.ratemyprofessors.com/professor/1789207",
  "Priyanka Gopinath": null,
  "Priyanka N A M": null,
  "Qi Yang": "https://www.ratemyprofessors.com/professor/2576815",
  "Rachel Crawford": "https://www.ratemyprofessors.com/professor/2640704",
  "Rachel Turner": "https://www.ratemyprofessors.com/professor/2708579",
  "Rafael Kaliski": null,
  "Rahul Balakrishna Balasubramaniam": "https://www.ratemyprofessors.com/professor/2889946",
  "Raina Levesque": "https://www.ratemyprofessors.com/professor/2855561",
  "Rakesh Jeyasingh": null,
  "Ram Nallamatti": null,
  "Ramen Bahuguna": "https://www.ratemyprofessors.com/professor/54071",
  "Ramin Moazeni": null,
  "Ranko Heindl": "https://www.ratemyprofessors.com/professor/1786195",
  "Raymond Hess / Carlie Pietsch": null,
  "Raymond Kwok": "https://www.ratemyprofessors.com/professor/742919",
  "Regina Arnold": "https://www.ratemyprofessors.com/professor/2394427",
  "Resa Kelly": "https://www.ratemyprofessors.com/professor/812091",
  "Richard Low": "https://www.ratemyprofessors.com/professor/85837",
  "Richard Mcnabb": "https://www.ratemyprofessors.com/professor/2686815",
  "Richie Tay": null,
  "Ricky Koonming Chan": "https://www.ratemyprofessors.com/professor/3038081",
  "Rita Cameron": null,
  "Rithik Reddy Katpally": null,
  "Robert Chun": "https://www.ratemyprofessors.com/professor/216637",
  "Robert Meyer / Carlie Pietsch": null,
  "Robert Meyer / Jonathan Miller": null,
  "Robert Meyer / Ryan Portner": null,
  "Robert Morelos-Zaragoza": null,
  "Robert Nicholson": "https://www.ratemyprofessors.com/professor/2594920",
  "Rodrigo Chen": null,
  "Roger Terrill": "https://www.ratemyprofessors.com/professor/452078",
  "Rohan Kuruvatti": null,
  "Rohit Sharma": null,
  "Roohi Vora": "https://www.ratemyprofessors.com/professor/516288",
  "Roshni Dhandamudi": null,
  "Ruijuan Niu": null,
  "Rula Khayrallah": "https://www.ratemyprofessors.com/professor/2208638",
  "Ruthu Shankar Lnu": null,
  "Ryan Duffy": null,
  "Ryan Portner / Hollianne Mcclure": "https://www.ratemyprofessors.com/professor/2219966",
  "Ryan Portner / Will Rizza": "https://www.ratemyprofessors.com/professor/2219966",
  "Ryan Skinnell": "https://www.ratemyprofessors.com/professor/2114775",
  "Ryan Smith": "https://www.ratemyprofessors.com/professor/2857461",
  "S V S Siva Narayana Naga Sesha Kollepara": null,
  "Sahika Vatan": "https://www.ratemyprofessors.com/professor/3065115",
  "Sai Anuraghav Savadam": null,
  "Sai Prasanna Kumar Varikallu": null,
  "Sai Srinivas Lakkakula": null,
  "Sai Vamsi Chilukuri": null,
  "Sai Vikram Adithya Bokka": null,
  "Saicharan Reddy Kadari": null,
  "Saied Rafati": null,
  "Samantha Kaplan": null,
  "Samuel Michael": "https://www.ratemyprofessors.com/professor/3101284",
  "Sanika Vijaykumar Karwa": null,
  "Sanjayvarma Pandeti / Bhawandeep Singh Harsh": null,
  "Sanjukta Sheth": null,
  "Sanket Kulkarni": "https://www.ratemyprofessors.com/professor/2985741",
  "Santosh Kc": null,
  "Saptarshi Sengupta": "https://www.ratemyprofessors.com/professor/2834186",
  "Sara Cook": "https://www.ratemyprofessors.com/professor/926719",
  "Sathvika Mamidi": null,
  "Sayma Akther": "https://www.ratemyprofessors.com/professor/2926663",
  "Seshadri Paravastu": "https://www.ratemyprofessors.com/professor/2617028",
  "Shai Silberman": "https://www.ratemyprofessors.com/professor/1963609",
  "Shaifali Singh": null,
  "Shaunak Mashalkar": "https://www.ratemyprofessors.com/professor/2869147",
  "Shawn Tran": "https://www.ratemyprofessors.com/professor/368773",
  "Sherri Harvey": "https://www.ratemyprofessors.com/professor/114573",
  "Shervin Ambrose": null,
  "Shireen Faraha Shaik": null,
  "Shiva Kumar Appam": null,
  "Shivani Sanjay Degloorkar": null,
  "Shravya Juluru": null,
  "Shreeyukta Singh": "https://www.ratemyprofessors.com/professor/2653862",
  "Shreyas Kulkarni": null,
  "Shubham Subhash Gaikwad": null,
  "Sieg Baluyot": "https://www.ratemyprofessors.com/professor/2982507",
  "Simon Seo": "https://www.ratemyprofessors.com/professor/3094937",
  "Sindhuja Ravi": null,
  "Smita Duorah": "https://www.ratemyprofessors.com/professor/1251316",
  "Sneha Odugoudar": null,
  "Sogol Jahanbekam": "https://www.ratemyprofessors.com/professor/2434360",
  "Soham Kapasi": null,
  "Sonia Cuellar-Ortiz": "https://www.ratemyprofessors.com/professor/2472558",
  "Soon Tee Teoh": "https://www.ratemyprofessors.com/professor/630528",
  "Sophie Aust": "https://www.ratemyprofessors.com/professor/2959093",
  "Sotoudeh Hamedi-Hagh": "https://www.ratemyprofessors.com/professor/629083",
  "Sotoudeh Hamedi-Hagh / Thuy Le": "https://www.ratemyprofessors.com/professor/629083",
  "Spoorthy Ananthaiah": "https://www.ratemyprofessors.com/professor/2118955",
  "Sreeja Manda": null,
  "Sriram Rao": "https://www.ratemyprofessors.com/professor/3041746",
  "Srivatsan Srinivasan": null,
  "Staff": null,
  "Stephanie Stepp": null,
  "Stephanie Velasquez": null,
  "Stephanie Wemusa": "https://www.ratemyprofessors.com/professor/2255564",
  "Steven Morgan": "https://www.ratemyprofessors.com/professor/504775",
  "Steven Rogalsky": null,
  "Steven Sepka": "https://www.ratemyprofessors.com/professor/788590",
  "Suharsh Cherukunnon Arippa": null,
  "Suma Nagral": null,
  "Suneuy Kim": "https://www.ratemyprofessors.com/professor/90503",
  "Supreeta Amin": "https://www.ratemyprofessors.com/professor/2449624",
  "Supriya Bhupathiraju": null,
  "Suzy Brookshire": "https://www.ratemyprofessors.com/professor/2953691",
  "Suzy Brookshire / Jonathan Miller": "https://www.ratemyprofessors.com/professor/2953691",
  "Tahereh Arabghalizi": "https://www.ratemyprofessors.com/professor/2926378",
  "Tahir Bachar Issa": "https://www.ratemyprofessors.com/professor/2733622",
  "Tan Nguyen": "https://www.ratemyprofessors.com/professor/1332414",
  "Tan Nguyen / Bhaskar Mantha": "https://www.ratemyprofessors.com/professor/1332414",
  "Taylor Arhar": null,
  "Tazmina Sharmin": "https://www.ratemyprofessors.com/professor/2832179",
  "Tejaswani Dasari": null,
  "Telvin Zhong": "https://www.ratemyprofessors.com/professor/3048474",
  "Thomas Austin": "https://www.ratemyprofessors.com/professor/2000580",
  "Thomas Cai": "https://www.ratemyprofessors.com/professor/2877327",
  "Thomas Madura": "https://www.ratemyprofessors.com/professor/2165292",
  "Thuy Le": "https://www.ratemyprofessors.com/professor/62049",
  "Thuy Le / Birsen Sirkeci": "https://www.ratemyprofessors.com/professor/62049",
  "Thuy Le / Chang Choo": "https://www.ratemyprofessors.com/professor/62049",
  "Thuy Le / Jonathan Ponniah": "https://www.ratemyprofessors.com/professor/62049",
  "Thuy Le / Juzi Zhao": "https://www.ratemyprofessors.com/professor/62049",
  "Thuy Le / Mohamed Badawy": "https://www.ratemyprofessors.com/professor/62049",
  "Thuy Le / Nader Mir": "https://www.ratemyprofessors.com/professor/62049",
  "Thuy Le / Robert Morelos-Zaragoza": "https://www.ratemyprofessors.com/professor/62049",
  "Thuy Le / Sotoudeh Hamedi-Hagh": "https://www.ratemyprofessors.com/professor/62049",
  "Thuy Le / Tri Caohuu": "https://www.ratemyprofessors.com/professor/62049",
  "Tianhao Jia": null,
  "Timothy Cech": "https://www.ratemyprofessors.com/professor/2896645",
  "Timothy Duren": null,
  "Timothy Hsu": null,
  "Toby Stuckey": null,
  "Tommy Chang": null,
  "Tony Pan": "https://www.ratemyprofessors.com/professor/1846866",
  "Tony Papanikolas": "https://www.ratemyprofessors.com/professor/3035803",
  "Toshi Bhat": "https://www.ratemyprofessors.com/professor/2961937",
  "Tri Caohuu": "https://www.ratemyprofessors.com/professor/62048",
  "Trisha Bergthold": "https://www.ratemyprofessors.com/professor/225871",
  "Truc Nguyen": null,
  "Twinkle Patel": null,
  "Tyeshia Sapp": null,
  "Tyler Morales": "https://www.ratemyprofessors.com/professor/3153259",
  "Ume Ali": "https://www.ratemyprofessors.com/professor/2617610",
  "Vakini Santhanakrishnan": "https://www.ratemyprofessors.com/professor/2714310",
  "Vasuda Bhatia": "https://www.ratemyprofessors.com/professor/2748069",
  "Venkata Kavya Katara": null,
  "Venkata Prudhvi Vellanki": null,
  "Venkata Satya Kanaka Madhav Gadhamsetty": null,
  "Venkata Sudha Vihari Chitrapu": null,
  "Victor Maraschin": "https://www.ratemyprofessors.com/professor/2703005",
  "Victoria Thorp": "https://www.ratemyprofessors.com/professor/2840854",
  "Vidya Rangasayee": "https://www.ratemyprofessors.com/professor/2039795",
  "Viet Nguyen": "https://www.ratemyprofessors.com/professor/1166854",
  "Vikhyath Shankargari": null,
  "Vineeth Kaza": null,
  "Vinh Nguyen": null,
  "Vishwa Samirbhai Shah": null,
  "Vishwa Shah": null,
  "Vrund Hetalkumar Shah": null,
  "Vrushali Arute": null,
  "Wasin So": "https://www.ratemyprofessors.com/professor/95115",
  "Weider Yu": "https://www.ratemyprofessors.com/professor/221912",
  "Wencen Wu": "https://www.ratemyprofessors.com/professor/2424635",
  "Wencen Wu / Kaikai Liu": "https://www.ratemyprofessors.com/professor/2424635",
  "Will Rizza / Jonathan Miller": "https://www.ratemyprofessors.com/professor/2886477",
  "Will Rizza / Ryan Portner": "https://www.ratemyprofessors.com/professor/2886477",
  "William Andreopoulos": "https://www.ratemyprofessors.com/professor/2534380",
  "William Hong": "https://www.ratemyprofessors.com/professor/3033874",
  "Wo-Tak Wu": "https://www.ratemyprofessors.com/professor/2885467",
  "Xavier Mendoza": null,
  "Xiao Wang": "https://www.ratemyprofessors.com/professor/3069365",
  "Yalda Edalat": "https://www.ratemyprofessors.com/professor/2652360",
  "Yan Chen": "https://www.ratemyprofessors.com/professor/2628898",
  "Yan Zhang": "https://www.ratemyprofessors.com/professor/2167518",
  "Yasmeen Abdeljabbar": "https://www.ratemyprofessors.com/professor/2958986",
  "Yeganeh Modirzadeh": "https://www.ratemyprofessors.com/professor/2532942",
  "Yuching Yang": "https://www.ratemyprofessors.com/professor/2380372",
  "Yue Luo": "https://www.ratemyprofessors.com/professor/2969087",
  "Yujin Hur": null,
  "Yulia Newton": "https://www.ratemyprofessors.com/professor/2599405",
  "Zachary Coustier": null,
  "Zairac Smith": "https://www.ratemyprofessors.com/professor/2959347",
  "Zak Espley": "https://www.ratemyprofessors.com/professor/3000457",
  "Zeel Jatinkumar Lia": null,
  "Zeel Jayeshkumar Soni": null,
  "Zehlia Babaci-Wilhite": "https://www.ratemyprofessors.com/professor/2328909",
  "Zenithbhai Chokshi": null,
  "Zeyu Gao": "https://www.ratemyprofessors.com/professor/2386906",
  "Zili Wu": null,
};

export default ProfessorLinksRMP;